apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  database-url: {{ .Values.backend.env.DATABASE_URL }}
  cors-origins: {{ .Values.backend.env.CORS_ORIGINS | quote }}