apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.postgresqlUsername | b64enc }}
  postgres-password: {{ .Values.postgres.postgresqlPassword | b64enc }}