apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medical-appointment-develop
  namespace: argocd
  labels:
    app: medical-appointment
    environment: develop
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=medical-appointment-backend,frontend=medical-appointment-frontend
    argocd-image-updater.argoproj.io/backend.update-strategy: semver
    argocd-image-updater.argoproj.io/frontend.update-strategy: semver
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^local$
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^local$
spec:
  project: default
  source:
    repoURL: https://github.com/SBillion/medical-appointment-config.git
    targetRevision: develop
    path: charts/medical-appointment
    helm:
      valueFiles:
        - values-develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: medical-appointment-develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        environment: develop
        app: medical-appointment