apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  api-base-url: {{ .Values.frontend.env.VITE_API_BASE_URL }}